### ISSUE TITLE
Discovery interviews synthesis

### ISSUE THREAD

**Issue by amberwreed** [18F/dotgov-support#13]
- [x] Journey map
- [ ] Problem statement
- [ ] Ecosystem map

**Comment by porta-antiporta** [comment]
https://drive.google.com/open?id=1qN4GgiibghC1wMWcyLRJaTFD92hToqhiKGzZ2c6I2Bg

**Comment by porta-antiporta** [comment]
https://docs.google.com/spreadsheets/d/1nwq4E2T4W4ASQ1hlxoV9vVE9c-sT55mwSfLZaM-5GA4/edit#gid=0

**Comment by porta-antiporta** [comment]
https://app.mural.ly/t/gsa6/m/gsa6/1502124329603/88cec96136318c78ab46fbd1120e722daa606be7
